services:
  db:
    image: pgvector/pgvector:0.8.0-pg17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=password1
      - POSTGRES_HOST_AUTH_METHOD=trust
